---
- name: Apply base configuration
  hosts: all
  roles:
    - base

- name: Configure web servers
  hosts: all
  roles:
    - web

- name: Configure database servers
  hosts: all
  roles:
    - db

- name: Configure monitoring
  hosts: all
  roles:
    - monitoring
