---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Start nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Create custom index page
  copy:
    content: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>Welcome to My Server</title>
      </head>
      <body>
          <h1>Hello from Ansible!</h1>
          <p>This page was created by Ansible automation.</p>
      </body>
      </html>
    dest: /var/www/html/index.html
